on: [push]
name: Package
jobs:
  package:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3
      - name: Zip into pak file
        run: |
          zip -r pak001-Free.pak Gfx/ License/ Models/ Sounds/
      - name: Zip compatible dev zip
        run: |
          curl --location -O https://github.com/yvt/openspades-paks/releases/download/r33/OpenSpadesDevPackage-r33.zip
          unzip OpenSpadesDevPackage-r33.zip
          rm OpenSpadesDevPackage-r33.zip
          rm Nonfree/pak000-Nonfree.pak
          cp pak001-Free.pak Nonfree
          cp License/Credits-pak001-Free.md Nonfree/LICENSE.md
          zip -r OpenSpadesDevPackage-r33.zip Nonfree OfficialMods
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "Assets"
          files: |
            pak001-Free.pak
            OpenSpadesDevPackage-r33.zip
